'use strict';
var yeoman = require('yeoman-generator');
var chalk = require('chalk');
var yosay = require('yosay');

module.exports = yeoman.generators.Base.extend({
  initializing: function () {
    this.pkg = require('../package.json');
  },

  prompting: function () {
    var done = this.async();

    this.log(yosay(
      'Welcome to ' + chalk.red(this.pkg.name) + '!'
    ));

    // var prompts = [{
    //   type: 'confirm',
    //   name: 'makePrivate',
    //   message: 'Would you like mark your app as private in your package.json?',
    //   default: true
    // }, {
    //   type: 'confirm',
    //   name: 'useStaticFileServer',
    //   message: 'Would you like to use st in order to serve your app?',
    //   default: true
    // }, {
    //   type: 'confirm',
    //   name: 'useLiveReload',
    //   message: 'Would you like to use LiveReload?',
    //   default: true
    // }, {
    //   type: 'confirm',
    //   name: 'openRepo',
    //   message: 'Would you mind staring this repo to support its development?',
    //   default: false
    // }, {
    //   type: 'confirm',
    //   name: 'initGit',
    //   message: 'Would you like to initialize this as a new GIT repo as soon as I\'m done?',
    // }];

    var prompts = [];

    this.prompt(prompts, function (props) {
      this.package = {
        name: 'pure-awesomeness',
        description: 'Generated by generator-webgl',
        repository: 'https://github.com/alexanderGugel/generator-webgl',
        author: {
          name: 'Alexander Gugel',
          email: 'alexander.gugel@gmail.com',
          url: 'https://github.com/alexanderGugel'
        },
        license: 'MIT',
        private: true
      };

      done();
    }.bind(this));
  },

  writing: function () {
    this.template('_package.json', 'package.json');
    this.template('_index.html', 'index.html');
    this.template('_index.js', 'index.js');
    this.template('_index.css', 'index.css');
    this.template('_editorconfig', '.editorconfig');
    this.template('_gitattributes', '.gitattributes');
    this.template('_gitignore', '.gitignore');
    this.template('_jshintrc', '.jshintrc');
    this.template('_README.md', 'README.md');
  },

  install: function () {
    this.installDependencies({
      bower: false
    });
  }
});
